version: '3.8'

services:
  project-nest_js-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-project-nest_js}'
    volumes:
      - ./project-nest_js-api-db:/var/lib/postgresql/project-nest_js

  project-nest_js-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-password}'
    restart: unless-stopped

volumes:
  project-nest_js-api-db: